spring:
  application.name: stores
  profiles:
    active: prod
  datasource:
    url: "jdbc:h2:mem:StoreDB"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082